file  has been updated

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,29 +1,28 @@
 #!/usr/bin/env bash
-# Transfers a file from our client to a server and tchec it :
 
-if [ $# -lt 4 ]
-then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit 1
+# Transfers a file from our client to a server and checks it:
+
+if [ $# -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
 
-# assignements Variable:
+# Assign variables:
+path_to_file="$1"
+ip="$2"
+username="$3"
+path_to_ssh_key="$4"
 
-path_to_file=$1
-ip=$2
-username=$3
-path_to_ssh_key=$4
+# Disable strict host key checking for SCP:
+scp_command="scp -o StrictHostKeyChecking=no -i $path_to_ssh_key $path_to_file $username@$ip:~/"
 
-#diasble strick host
+# Execute SCP command:
+$scp_command
 
-scp -o "StrictHostKeyCheking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@ip:~/"
-
-# 0/1 transfere behavior
-
-if [ $? -eq 0 ]
-then
-	echo "trasnfered succeddfuly"
+# Check the exit status of SCP (0 for success, non-zero for failure):
+if [ $? -eq 0 ]; then
+    echo "Transfer successful"
 else
-	echo"transfer denied"
+    echo "Transfer denied"
 fi
 
